name: Daily Notify Test

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Run Index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: PHP Version
        run: php --version

      - name: Set environment variable
        run: |
          export app_id=${{ secrets.APP_ID }}
          export app_secret=${{ secrets.APP_SECRET }}
          export template_id=${{ secrets.TEMPLATE_ID }}
          export open_id=${{ secrets.OPEN_ID }}
      - name: Execute PHP Script
        run: php index.php
